name: Deploy to motivator-production

on:
  push:
    branches: [deploy-demo-ai]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install backend deps
        run: npm ci
        working-directory: functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase Project credentials
        run: echo '${{ secrets.FIREBASE_TOKEN }}' > $HOME/firebase-token.json

      - name: Authenticate FIREBASE_TOKEN
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-token.json" >> $GITHUB_ENV

      - name: Inject environment.ci.ts
        run: |
          echo "export const environment = $NG_ENVIRONMENT" > src/environments/environment.ci.ts
        env: 
          NG_ENVIRONMENT: |
            {
              api: {
                firebaseConfig: {
                    apiKey: "AIzaSyChThmAwa_1YsnaaxYqRsgHsfUKpsVySH4",
                    authDomain: "ai-demo-f9abe.firebaseapp.com",
                    projectId: "ai-demo-f9abe",
                    storageBucket: "ai-demo-f9abe.firebasestorage.app",
                    messagingSenderId: "37077028461",
                    appId: "1:37077028461:web:24bc97ddc8d22039397964",
                  },
              },
              production: true,
              region: 'me-west1',
              title: 'production ci',
            }

      - name: Build frontend (CI Config)
        run: npm run build:ci
            
      - name: Compile backend
        run: npm run srv:compile

      - name: Deploy to Firebase
        run: firebase deploy --force --project ai-demo-f9abe

